#!/bin/bash

a=$1
b=$2

if [ $# -ne 2 ]; then
 echo "please enter two values"

elif [ $a -eq $b ]; then
 echo "both no are same"

elif [ $a -gt $b ]; then
 echo "$a is bigger than $b"

else
 echo "$b is bigger than $a"

fi
